### ISSUE TITLE
Error.captureStackTrace is not supported by all browsers

### ISSUE THREAD

**Issue by Madd0g** [building5/promise-timeout#3]
IE11 throwing errors in the TimeoutError constructor.

Is there a recommended polyfill for Error.captureStackTrace?

**Comment by leedm777** [comment]
@Madd0g Just a polyfill probably won't get you there, since the file also has `require('util').inherits()` for the class inheritance.

I just pushed a branch `portable-timeout` where I use the output from Babel.js for extending the `Error` class. Can you try it and see if it works in IE11?

**Comment by Madd0g** [comment]
Huh, I'm using webpack+babel, I guess they solved the `require('util')` problem for me, because the only error I was getting is for the `captureStackTrace`.

While waiting for you to reply, I added just a tiny if statement to check if `captureStackTrace` exists on Error and it solved the problem for me.

I tried that branch in my IE11 VM and this is what I get from that branch:

`Unhandled promise rejection TypeError: Invalid operand to 'instanceof': Function expected`.

**Comment by leedm777** [comment]
@Madd0g I found a [StackOverflow comment](https://stackoverflow.com/questions/1382107/whats-a-good-way-to-extend-error-in-javascript#comment17126532_5251506) which seems like a good approach. I've updated my branch. Let me know how it works.

**Comment by iray-tno** [comment]
@leedm777 I faced the same problem. And the portable-promise branch works for me. Thanks!

**Comment by leedm777** [comment]
Fix published with v1.3.0. PRs/issues welcome if there are further problems.
